// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleApi.Data;

#nullable disable

namespace PeopleApi.Migrations
{
    [DbContext(typeof(PeopleApiDbContext))]
    [Migration("20260122091737_FixForeignKey")]
    partial class FixForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeopleApi.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Körsång är en form av vokalmusik där en grupp människor sjunger tillsammans, oftast under ledning av en dirigent. Det är en kollektiv konstform som bygger på samspel, gemenskap och harmonisering av röster.",
                            Title = "Körsång"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Träning är fysisk aktivitet med mål att förbättra styrka, kondition, rörlighet eller färdigheter genom regelbunden ansträngning, där kroppen anpassar sig genom att bygga upp muskler, stärka skelettet och förbättra hjärnans funktioner för att hantera ökad stress. Det involverar planering med specifika mål, val av övningar (som knäböj, bänkpress), rätt intensitet och återhämtning, ofta rekommenderat minst två gånger i veckan för styrka, med variation och progression för bästa resultat. ",
                            Title = "Träning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Programmering är konsten att skriva instruktioner (kod) i ett programmeringsspråk som en dator eller annan apparatur kan förstå för att utföra specifika uppgifter, lösa problem, skapa appar, webbplatser eller automatisera processer; det är i grunden logiskt tänkande och att bryta ner en uppgift i små, exakta steg (en algoritm) som sedan översätts till maskinkod. Processen inkluderar analys, planering, kodning, testning och felsökning. ",
                            Title = "Programmering"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Matlagning är konsten, vetenskapen och hantverket att använda värme för att omvandla livsmedelsråvaror till färdig mat.Syftet är att göra maten mer välsmakande, lättsmält, näringsrik eller säker att äta. Det innefattar en rad tekniker, från grundläggande förberedelser till avancerade metoder som kräver precision.",
                            Title = "Matlagning"
                        });
                });

            modelBuilder.Entity("PeopleApi.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonInterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonInterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonInterestId = 1,
                            Url = "https://www.svenskakyrkan.se/sofia/sofia-nova"
                        },
                        new
                        {
                            Id = 2,
                            PersonInterestId = 1,
                            Url = "https://www.sverigeskorforbund.se/"
                        },
                        new
                        {
                            Id = 3,
                            PersonInterestId = 2,
                            Url = "https://www.sats.se/"
                        },
                        new
                        {
                            Id = 4,
                            PersonInterestId = 3,
                            Url = "https://chasacademy.se/"
                        },
                        new
                        {
                            Id = 5,
                            PersonInterestId = 4,
                            Url = "https://hjkk.se/"
                        },
                        new
                        {
                            Id = 6,
                            PersonInterestId = 5,
                            Url = "https://www.koket.se/"
                        },
                        new
                        {
                            Id = 7,
                            PersonInterestId = 6,
                            Url = "https://csharpskolan.se/"
                        },
                        new
                        {
                            Id = 8,
                            PersonInterestId = 6,
                            Url = "https://learn.microsoft.com/en-us/dotnet/csharp/"
                        });
                });

            modelBuilder.Entity("PeopleApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Mohammed",
                            LastName = "Malik",
                            PhoneNr = "072-789 23 41"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sara",
                            LastName = "Wennergren",
                            PhoneNr = "076-346 44 81"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Lydia",
                            LastName = "Abou",
                            PhoneNr = "073-339 15 47"
                        });
                });

            modelBuilder.Entity("PeopleApi.Models.PersonInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonsInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 1,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 4,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 3,
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("PeopleApi.Models.Link", b =>
                {
                    b.HasOne("PeopleApi.Models.PersonInterest", "PersonInterest")
                        .WithMany("Links")
                        .HasForeignKey("PersonInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("PeopleApi.Models.PersonInterest", b =>
                {
                    b.HasOne("PeopleApi.Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleApi.Models.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PeopleApi.Models.Interest", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("PeopleApi.Models.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("PeopleApi.Models.PersonInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
